server:
  port: 9083
spring:
  application:
    name: proxy
  cloud:
    gateway:
      routes:
        - id: app
          uri: lb://app
          predicates:
            - Path=/app/**
          filters:
            - StripPrefix=1
            - name: Retry
              args:
                retries: 3
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - name: Retry
              args:
                retries: 3
eureka:
  client:
    healthcheck:
      enabled: true
logging:
  level:
    org.springframework: debug

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus