spring:
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: auth
server:
  port: 9081

eureka:
  client:
    healthcheck:
      enabled: true
logging:
  level:
    org.springframework: debug